apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
  labels:
    owner: GuyDvorkin
    project: simple-flask-app-k8s-adv-lesson-10
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
        owner: GuyDvorkin
        project: simple-flask-app-k8s-adv-lesson-10
    spec:
      containers:
      - name: simple-flask-app
        image: dvorkinguy/simple-flask-app:3.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
