apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app
  labels:
    owner: GuyDvorkin
    project: simple-flask-app-k8s-adv-lesson-10
spec:
  type: LoadBalancer
  selector:
    app: simple-flask-app
  ports:
  - port: 3030
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app-clusterip
  labels:
    owner: GuyDvorkin
    project: simple-flask-app-k8s-adv-lesson-10
spec:
  type: ClusterIP
  selector:
    app: simple-flask-app
  ports:
  - port: 3030
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app-nodeport
  labels:
    owner: GuyDvorkin
    project: simple-flask-app-k8s-adv-lesson-10
spec:
  type: NodePort
  selector:
    app: simple-flask-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
    nodePort: 31000