apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-multipod
  labels:
    owner: GuyDvorkin
    project: multi-fun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
        owner: GuyDvorkin
        project: multi-fun
    spec:
      containers:
      - name: my-web
        image: dvorkinguy/simple-flask-app:3.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

      - name: not-my-web
        image: tomcat:8.5.38
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels: 
    env: prod
    owner: GuyDvorkin
spec:
  type: LoadBalancer
  selector:
    project: multi-fun
    app: simple-flask-app
    name: my-web
  ports:
    - name: my-web-app-listener
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: not-my-web-service
  labels: 
    env: prod
    owner: GuyDvorkin
spec:
  type: LoadBalancer
  selector:
    project: multi-fun
    app: simple-flask-app
    name: not-my-web
  ports:
    - name: not-my-web-app-listener
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app-multipod-service
spec:
  selector:
    app: simple-flask-app-multipod
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31923
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
    nodePort: 31924
  type: LoadBalancer