apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-deployment-autoscaling
spec:
  selector:
    matchLabels:
      app: simple-flask-app
      project: my-example
  template:
    metadata:
      labels:
        app: simple-flask-app
        project: my-example
    spec:
      containers:
      - name: simple-flask-app
        image: dvorkinguy/simple-flask-app:3.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling-pod-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-flask-app-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
    env: prod
    owner: DvorkinGuy
spec:
  selector:
    app: simple-flask-app
    project: my-example
  ports:
  - name: app-listener
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
