apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
  namespace: time-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dvorkinguy/time-app-frontend-dev:latest
          ports:
            - containerPort: 5000            