apiVersion: v1
kind: Service
metadata:
  name: time-app-service
  namespace: time-app-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer