apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: httpd
    image: httpd:latest
    ports:
    - containerPort: 80
    resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
