apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    name: my-web
spec:
  containers:
  - name: my-web
    image: dvorkinguy/simple-flask-app:3.0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000