apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    name: my-app
    env: prod
    tier: frontend
    owner: GuyDvorkin
    
spec:
  containers:
  - name: container-web
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

  - name: container-api
    image: tomcat:8.5.38
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080