apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app: my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: mrwolf2
  template:
    metadata:
      labels:
        project: mrwolf2
    spec:
      containers:
        - name: mrwolf2-web
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080
