apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-multipod
  labels:
    owner: GuyDvorkin
    project: multi-fun
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
        owner: GuyDvorkin
        project: multi-fun # Service will look for those PODS Labels
    spec:
      containers:
      - name: my-web
        image: dvorkinguy/simple-flask-app:3.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

      - name: not-my-web
        image: tomcat:8.5.38
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

      
---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app-multipod
  labels: 
    env: prod
    owner: GuyDvorkin
spec:
  type: LoadBalancer
  selector:
    project: multi-fun # Selecting PODS with those labels
  ports:
    - name: my-web-app-listener
      protocol: TCP
      port: 80        # Port on Load Balancer
      targetPort: 5000  # Port on PODS
    
    - name: not-my-web-app-listener
      protocol: TCP
      port: 8888       # Port on Load Balancer
      targetPort: 8080  # Port on PODS
