apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-ingress-cluster
  region: us-west-2
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    minSize: 2
    maxSize: 3
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/oregon-us-west-2.pub
    availabilityZones: ["us-west-2a", "us-west-2b"]