apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: dvorkinguy/simple-flask-app:3.1.0
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"