apiVersion: v1
kind: Service
metadata:
  name: my-single-pod1-service
  labels:
    env: prod
    owner: GuyDvorkin
spec:
  selector:
    project: mrwolf1 # Selecting PODS with those labels
  ports:
  - name: app1-listener
    protocol: TCP
    port: 80 # Port on Load Balancer
    targetPort: 80 # Port on POD
  type: LoadBalancer
